# name: Deploy to GitHub Pages

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./github_pages_speak_and_translate  # Updated working directory

#     steps:
#       - uses: actions/checkout@v4
      
#       - name: Set up Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.29.2'
#           channel: 'stable'
      
#       - run: flutter config --enable-web
#       - run: flutter pub get
#       - run: flutter build web --release --base-href "/speak_and_translate_app/"
        
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: github.ref == 'refs/heads/main'
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./github_pages_speak_and_translate/build/web
#           force_orphan: true

# permissions:
#   contents: write


name: Auto-Build and Deploy

on:
  push:
    branches: ["main"]
    paths:
      - 'github_pages_speak_and_translate/lib/**'  # Only trigger on changes to lib folder.
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
      
      - name: Enable web
        run: flutter config --enable-web
      
      - name: Build Flutter web app
        working-directory: ./github_pages_speak_and_translate
        run: flutter build web --release --base-href "/speak_and_translate_app/"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_pages_speak_and_translate/build/web
          force_orphan: true
          
permissions:
  contents: write