# name: Deploy to GitHub Pages

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
      
#       - name: Set up Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.27.1'
#           channel: 'stable'
      
#       - name: Install dependencies
#         run: flutter pub get
      
#       - name: Enable web
#         run: flutter config --enable-web
      
#       - name: Build web
#         run: flutter build web --release --base-href /speak_and_translate_app/
        
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: github.ref == 'refs/heads/main'
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./build/web
#           force_orphan: true

# permissions:
#   contents: write



name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable web
        run: flutter config --enable-web
      
      - name: Build web
        run: |
          flutter build web --release --base-href "/"
          # Create a .nojekyll file to bypass Jekyll processing
          touch build/web/.nojekyll
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          cname: null # Set to your custom domain if you have one

permissions:
  contents: write